### ISSUE TITLE
NanoRange failed with error C2903, C2760, C2187 when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [tcbrindle/NanoRange#27] opened 2018-07-03 06:51 UTC
Hi All,
I tried to build NanoRange with VS2017 Update 7 on Windows. It failed to build due to the error C2903, C2760, C2187. This issue can be reproduced from master revision 07be3bf. Could you please help take a look at this? Thanks!

**Expected behavior:**
build successfully

**Actual behavior:**
The whole log file please see attachment.
[NanoRange_x86_build.log](https://github.com/tcbrindle/NanoRange/files/2157942/NanoRange_x86_build.log)      
       d:\nanorange\src\include\nanorange\detail\common_reference.hpp(144,59): error C2903:     using type = std::add_cv_t<typename xref<A>::template type<U>>; [D:\NanoRange\build_x86\test\test_nanorange.vcxproj]
       d:\nanorange\src\include\nanorange\detail\common_reference.hpp(144,59): error C2903:                                                           ^ [D:\NanoRange\build_x86\test\test_nanorange.vcxproj]
         d:\nanorange\src\include\nanorange\detail\common_reference.hpp(144,41): error C2760:  syntax error: unexpected token '::', expected 'id-expression' [D:\NanoRange\build_x86\test\test_nanorange.vcxproj]
       d:\nanorange\src\include\nanorange\detail\common_reference.hpp(144,41): error C2760:     using type = std::add_cv_t<typename xref<A>::template type<U>>; [D:\NanoRange\build_x86\test\test_nanorange.vcxproj]
       d:\nanorange\src\include\nanorange\detail\common_reference.hpp(144,41): error C2760:                                         ^ [D:\NanoRange\build_x86\test\test_nanorange.vcxproj]
         d:\nanorange\src\include\nanorange\detail\common_reference.hpp(144,64): error C2187:  syntax error: 'identifier' was unexpected here [D:\NanoRange\build_x86\test\test_nanorange.vcxproj]
       d:\nanorange\src\include\nanorange\detail\common_reference.hpp(144,64): error C2187:     using type = std::add_cv_t<typename xref<A>::template type<U>>; [D:\NanoRange\build_x86\test\test_nanorange.vcxproj]
       d:\nanorange\src\include\nanorange\detail\common_reference.hpp(144,64): error C2187:                                                                ^ [D:\NanoRange\build_x86\test\test_nanorange.vcxproj]

**Steps to reproduce the behavior:**
1. Open VS2017 x86 Native tools command tool
2. git clone https://github.com/tcbrindle/nanorange d:\NanoRange\src
3. cd D:\NanoRange
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DCMAKE_CXX_STANDARD=17 ..\src\
6. msbuild /m /p:Configuration=Release;Platform=Win32 nanorange.sln /t:Rebuild

Thanks,
Shanshan

**Comment by tcbrindle** [comment] 2018-07-03 11:13
Thanks for the thorough bug report, I'll take a look

**Comment by tcbrindle** [comment] 2018-07-03 15:15
Turns out I wasn't using the latest MSVC build, but I've just updated to 19.14.26431.0 and still can't reproduce the error.

**Comment by tcbrindle** [comment] 2018-07-04 11:29
Hi @shanshan0309 -- I'm going to close this issue as it sounds like it's fixed in the latest MSVC 15.7 build. If you come across any more problems with NanoRange then please do file them.

**Closed by tcbrindle** 2018-07-04 11:29 UTC

**Comment by shanshan0309** [comment] 2018-07-06 02:10
Thank you Tristan.
